apiVersion: v1
kind: Service
metadata:
  name: inventory-db
  labels:
    app: inventory-db
spec:
  clusterIP: None
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: inventory-db
