apiVersion: v1
kind: Service
metadata:
  name: users-service
  labels:
    app: users-service
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
  selector:
    app: users-service
